name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # or 3.10, 3.9 depending on your project

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 linter
        run: flake8 .
