name: Secrets Scan

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to check for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--no-git -v"  # Scan current working dir only, verbose output
